// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.TuyenTM.Models;

public partial class AppointmentsNganVHH
{
    public int AppointmentNganVHHID { get; set; }

    public DateTime AppointmentDateTime { get; set; }

    public int Duration { get; set; }

    public string Status { get; set; }

    public int ConsultantID { get; set; }

    public string MeetingLink { get; set; }

    public int? FeedbackRating { get; set; }

    public string FeedbackComments { get; set; }

    public bool? IsCancelled { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<UserAppointmentsNganVHH> UserAppointmentsNganVHHs { get; set; } = new List<UserAppointmentsNganVHH>();
}