// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.TuyenTM.Models;

public partial class CoursesQuangTNV
{
    public int CourseQuangTNVID { get; set; }

    public string Title { get; set; }

    public string AgeGroup { get; set; }

    public string Category { get; set; }

    public int DurationInMinutes { get; set; }

    public string InstructorName { get; set; }

    public string ContentURL { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsActive { get; set; }

    public decimal? Rating { get; set; }

    public virtual ICollection<UserCoursesTuyenTM> UserCoursesTuyenTMs { get; set; } = new List<UserCoursesTuyenTM>();
}