// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.TuyenTM.Models;

public partial class OrganizationsTuyenTM
{
    public int OrganizationTuyenTMID { get; set; }

    public string OrganizationName { get; set; }

    public string Type { get; set; }

    public string Address { get; set; }

    public string ContactEmail { get; set; }

    public string ContactPhone { get; set; }

    public string Website { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool? IsPartner { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<OrganizationProgramsTuyenTM> OrganizationProgramsTuyenTMs { get; set; } = new List<OrganizationProgramsTuyenTM>();
}