// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.TuyenTM.Models;

public partial class SurveyQuestionsQuangTNV
{
    public int QuestionQuangTNVID { get; set; }

    public int SurveyID { get; set; }

    public string QuestionText { get; set; }

    public string QuestionType { get; set; }

    public string Options { get; set; }

    public bool? IsRequired { get; set; }

    public int QuestionOrder { get; set; }

    public int? RiskWeight { get; set; }

    public string HelpText { get; set; }

    public int? DependsOnQuestionID { get; set; }

    public string DependsOnAnswer { get; set; }

    public string ImageURL { get; set; }

    public virtual SurveysNamND Survey { get; set; }
}