// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.TuyenTM.Models;

public partial class UserCoursesTuyenTM
{
    public int UserCourseTuyenTMID { get; set; }

    public int UserID { get; set; }

    public int CourseID { get; set; }

    public DateTime EnrollmentDate { get; set; }

    public DateTime? CompletionDate { get; set; }

    public decimal? Progress { get; set; }

    public int? Score { get; set; }

    public bool? CertificateIssued { get; set; }

    public int? Rating { get; set; }

    public DateTime? LastAccessDate { get; set; }

    public virtual CoursesQuangTNV Course { get; set; }

    public virtual UsersTuyenTM User { get; set; }
}