// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.TuyenTM.Models;

public partial class UserSurveysNamND
{
    public int UserSurveyNamNDID { get; set; }

    public int? UserID { get; set; }

    public int SurveyID { get; set; }

    public DateTime SubmissionDate { get; set; }

    public int? RiskScore { get; set; }

    public string Recommendations { get; set; }

    public int? CompletionTime { get; set; }

    public bool? IsAnonymous { get; set; }

    public string ResultSummary { get; set; }

    public virtual SurveysNamND Survey { get; set; }

    public virtual UsersTuyenTM User { get; set; }
}