// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.TuyenTM.Models;

public partial class UserAppointmentsNganVHH
{
    public int UserAppointmentNganVHHID { get; set; }

    public int UserID { get; set; }

    public int AppointmentID { get; set; }

    public DateTime BookingDate { get; set; }

    public string PrimaryReason { get; set; }

    public bool? FollowUpRequired { get; set; }

    public bool? PreAppointmentSurveyCompleted { get; set; }

    public bool? PostAppointmentFeedbackProvided { get; set; }

    public string AdditionalNotes { get; set; }

    public string FollowUpNotes { get; set; }

    public virtual AppointmentsNganVHH Appointment { get; set; }
}